[package]
name = "pn_bitwister"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pncalc = { version = "0.1.0", path = "../pncalc" }
rustyline = "12.0.0"
